@echo off
echo Starting AI Cyber Defense System...

echo Starting AI Engine (Port 8000)...
start cmd /k "title AI Engine & C:\Users\Sanjana\AppData\Local\Programs\Python\Python314\python.exe -m uvicorn ai_engine.main:app --port 8000"

echo Starting Target App (Port 9000)...
start cmd /k "title Target App & C:\Users\Sanjana\AppData\Local\Programs\Python\Python314\python.exe -m uvicorn app.main:app --port 9000"

echo Starting Reverse Proxy (Port 7000)...
start cmd /k "title Reverse Proxy & C:\Users\Sanjana\AppData\Local\Programs\Python\Python314\python.exe -m uvicorn proxy.main:app --port 7000"

echo Starting React Dashboard...
start cmd /k "title Dashboard & cd dashboard & npm run dev"

echo Waiting a few seconds for servers to start before launching the attacker...
timeout /t 5

echo Starting Attacker Simulation...
start cmd /k "title Attacker & C:\Users\Sanjana\AppData\Local\Programs\Python\Python314\python.exe attacker/attacker.py"

echo All services launched! Please check your browser for the dashboard (usually http://localhost:5173)
